### ISSUE TITLE
Question: So VisNet is a corpus of datasets, not visual designs?

### ISSUE THREAD

**Issue by chenzhutian** [mitmedialab/viznet#1]
Thanks for your great work!
As my understanding, VisNet is a corpus of datasets (mostly in tabular format), rather than a corpus of dataset-visualization pairs.
Am I correct?

**Comment by kevinzenghu** [comment]
Hi @chenzhutian, you are correct! VizNet provides access to tabular datasets, not dataset-visualization pairs.

For Plotly dataset-visualization pairs you can see the [https://github.com/mitmedialab/vizml](VizML repository).
